# Python Data Types 
##### 1. Numeric Data Type    => (Integer, Float, Complex)
##### 2. Boolean Data Type    => (TRUE, FALSE)
##### 3. Binary Data Type    => (bytes, bytearray, memoryview)
##### 4. Sequence Data Type    => (List, Tuple, Range, Array, String)
##### 5. Set Data Type    => (Frozenset, Set)
##### 6. Mapping Data Type    => (Dictionary)
##### 7. Data Frame    => (See the Data Frame Image)

### 1. Numeric Data Type    => (Integer, Float, Complex)

#### Integer (int)
#### Float
#### Complex

In [1]:
x = 10 
y = 10.5
z = 10+5j    # 10 is real number and 5j is imaginary

In [2]:
type(x)

int

In [3]:
type(y)

float

In [4]:
type(z)

complex

In [5]:
isinstance(z, complex)

True

In [6]:
isinstance(10, float)

False

In [7]:
isinstance(100, int)

True

In [9]:
isinstance(10.10, float)

True

In [10]:
# int convert to float

x =25
n = float(x)

In [11]:
n

25.0

In [12]:
type(n)

float

In [13]:
n = int(n)
type(n)

int

In [14]:
# int convert to complex
n = complex(n)

In [15]:
n

(25+0j)

In [16]:
type(n)

complex

In [17]:
# float convert to complex
n = 25.10
n = complex(n)
n

(25.1+0j)

You can not go from complex to integer or float data type but you can go from integer or float to complex.

In [18]:
n = 25+0j
n

(25+0j)

In [19]:
type(n)

complex

In [22]:
n = int(n)    # You can not go from complex to integer or float data type but you can go from integer or float to complex.

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [21]:
n = float(n)    # You can not go from complex to integer or float data type but you can go from integer or float to complex.

TypeError: float() argument must be a string or a real number, not 'complex'

In [23]:
n = complex(input('Enter your complex number: '))

Enter your complex number:  1+0j

In [24]:
n

(1+0j)

In [43]:
n = complex(input('Enter your complex number: '))

Enter your complex number:  2+5j

In [44]:
type(n)

complex

### 2. Boolean Data Type    => (TRUE, FALSE)

#### TRUE
#### FALSE

In [52]:
x = True
y = False

In [53]:
x

True

In [54]:
y

False

### 3. Binary Data Type    => (bytes, bytearray, memoryview)

#### bytes

#### bytearray

In [143]:
byte_arr = bytearray('ABCDE', 'utf-8')

In [144]:
type(byte_arr)

bytearray

In [145]:
byte_arr

bytearray(b'ABCDE')

#### memoryview

In [147]:
memoryview(byte_arr)

In [152]:
memoryview(byte_arr)[0]    # [0] = A value,    # (ASCII code A = 65, a = 97)

97

In [155]:
# Value Replace (A = a) (65 = 97)


mv = memoryview(byte_arr)
mv[0] = 97

In [160]:
memoryview(byte_arr)[0]

97

In [159]:
byte_arr

bytearray(b'aBCDE')

### 4. Sequence Data Type    => (List, Tuple, Range, Array, String)

#### List [ ]

In [68]:
l = [1,2,3,4,5,True,[1,2],'Engineer',(1,2,3)]
l

[1, 2, 3, 4, 5, True, [1, 2], 'Engineer', (1, 2, 3)]

In [69]:
l[7]

'Engineer'

In [70]:
l[-3]

[1, 2]

In [71]:
l[-1][-2]

2

In [73]:
type(l)

list

In [74]:
isinstance(l, list)

True

#### Tuple ( )

In [75]:
t = (1,2,3,4,5,'Data')
t

(1, 2, 3, 4, 5, 'Data')

In [76]:
t[0]

1

In [78]:
t[0:5]    # Colon means to : 0 to 5-1

(1, 2, 3, 4, 5)

#### Range ( )

In [80]:
r = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
r

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [86]:
# 1st case

r = range(10)    
r

range(0, 10)

In [84]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7
8
9

In [88]:
# 2nd case

r = range(5,20)    

for i in r:
    print(i)

5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [107]:
# 3 rd case

r = range(5,20,2)    # Value 2 increse

for i in r:
    print(i)

5
7
9
11
13
15
17
19

In [92]:
# 4rd case

r = range(20,5,-2)

for i in r:
    print(i)

20
18
16
14
12
10
8
6

#### Array ( )

An array stores values of the same type. 

Does not store multiple types of values

In [25]:
import array as ar

In [26]:
a = ar.array([1,2,3,4,5])    
a

TypeError: array() argument 1 must be a unicode character, not list

In [27]:
a = ar.array('i',[1,2,3,4,5])    # Array integer type-code: i 
a

array('i', [1, 2, 3, 4, 5])

In [100]:
type(a)

array.array

In [101]:
a = ar.array('i',[10.5,2.5,3,4,5])
a

TypeError: 'float' object cannot be interpreted as an integer

In [102]:
a = ar.array('f',[1,2,3,4,5])    # Array float type-code: f 
a

array('f', [1.0, 2.0, 3.0, 4.0, 5.0])

#### String

In [103]:
x = 'Data Engineer'
x

'Data Engineer'

In [104]:
type(x)

str

In [105]:
# For Multiple Line 

x = '''
I am an 
Data Engineer
'''

x

'\nI am an \nData Engineer\n'

In [106]:
type(x)

str

### 5. Set Data Type    => (Frozenset, Set)

#### We will know in detail later.

#### Set { }

In [108]:
s = {1, 2, 3, 4, 5}
s

{1, 2, 3, 4, 5}

In [110]:
type(s)

set

#### Frozenset

### 5. Mapping Data Type    => (Dictionary)

#### Dictionary { }

In [111]:
dic = {
    'University': 'WUB',
    'Dept': 'Data Science'
}

dic

{'University': 'WUB', 'Dept': 'Data Science'}

In [116]:
type(dic)

dict

In [115]:
dic.keys()

dict_keys(['University', 'Dept'])

In [117]:
dic.values()

dict_values(['WUB', 'Data Science'])

### 7. Data Frame    => (See the Data Frame Image)

In [133]:
import pandas as pd

# For CSV file
df = pd.read_csv('Example data set.csv')            # For Excel File ->> df = pd.read_excel('Example data set')
df

    Id_No               Name  Age    District    Salary
0    1001  Tanmoy Khan Akash   29       Dhaka     20000
1    1002        Fariya Asha   25       Paris    300000
2    1003      Tamanna Haque   26  Munshiganj    100000
3    1004      Tanzila Akter   25       Dhaka     25000
4    1005     Yeasin Shikder   26   Gopalganj     15000
5    1006         Abir Hosin   22       Feeni     27000
6    1007       Shakil Ahmed   28   Gopalganj     10000
7    1008          Topu Dash   35      Khulna     14000
8    1009        Emon Podder   33      Narail      5000
9    1010         Nizum Khan   20   Gopalganj      4000
10   2001        Alida Molla   40    Bagerhat     25000
11   2002       Khaokan Khan   55   Gopalganj     50000
12   2003          Dipu Khan   48     Fardpur    200000
13   2004              Rikta   38      Khulna     50000
14   2005             Rafeja   45   Gopalganj    100000
15   2006        Kamrul Khan   58      Sylhet    500000
16   2007  Moniruzzaman Khan   49      Bogura  10000000
17   2008       Mukul Hossen   39      Kustia    400000
18   2009        Talha Molla   15    Rajshahi      2000
19   2010        Ahmed Molla   10    Bagerhat      1000

In [131]:
df.head()

   Id_No               Name  Age    District  Salary
0   1001  Tanmoy Khan Akash   29       Dhaka   20000
1   1002        Fariya Asha   25       Paris  300000
2   1003      Tamanna Haque   26  Munshiganj  100000
3   1004      Tanzila Akter   25       Dhaka   25000
4   1005     Yeasin Shikder   26   Gopalganj   15000

In [135]:
df.head(10)

   Id_No               Name  Age    District  Salary
0   1001  Tanmoy Khan Akash   29       Dhaka   20000
1   1002        Fariya Asha   25       Paris  300000
2   1003      Tamanna Haque   26  Munshiganj  100000
3   1004      Tanzila Akter   25       Dhaka   25000
4   1005     Yeasin Shikder   26   Gopalganj   15000
5   1006         Abir Hosin   22       Feeni   27000
6   1007       Shakil Ahmed   28   Gopalganj   10000
7   1008          Topu Dash   35      Khulna   14000
8   1009        Emon Podder   33      Narail    5000
9   1010         Nizum Khan   20   Gopalganj    4000

In [137]:
df.shape

(20, 5)

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id_No     20 non-null     int64
 1   Name      20 non-null     object
 2   Age       20 non-null     int64
 3   District  20 non-null     object
 4   Salary    20 non-null     int64
dtypes: int64(3), object(2)
memory usage: 932.0+ bytes